let x;
try {
    x = 1;
}
catch (e) {}


console.log (x);